/// Golden Rules enforcement tests — generated by spine-rules.
use spine_rules::golden_rules_suite;

golden_rules_suite! {
    binary: env!("CARGO_BIN_EXE_rvl"),
    operator_json: include_str!("../operator.json"),
    source_files: &["src/refusal/codes.rs", "src/output/json.rs"],
    fixture_success_args: &[
        "tests/fixtures/basic_old.csv",
        "tests/fixtures/basic_new.csv",
        "--json", "--no-witness",
    ],
    fixture_refusal_args: &[
        "/nonexistent/old.csv",
        "/nonexistent/new.csv",
        "--json", "--no-witness",
    ],
}
